<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="ModifyEvent.aspx.cs" Inherits="ModifyEvent" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div class="contents">
        <img  src="images/title_myprofile.gif" />
        <div>
            <asp:ScriptManager ID="ScriptMgr1" runat="server">
            </asp:ScriptManager>
            <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="socialeventid"
                DataSourceID="SqlDataSource1" OnRowUpdating="GridView1_RowUpdating" OnRowUpdated="GridView1_RowUpdated">
                <Columns>
                    <asp:BoundField DataField="socialeventid" HeaderText="socialeventid" InsertVisible="False"
                        ReadOnly="True" SortExpression="socialeventid" />
                    <asp:BoundField DataField="eventname" HeaderText="eventname" SortExpression="eventname" />
                    <asp:BoundField DataField="eventtype" HeaderText="eventtype" SortExpression="eventtype" />
                    <asp:BoundField DataField="eventdetails" HeaderText="eventdetails" SortExpression="eventdetails" />
                    <asp:TemplateField HeaderText="startdate">
                        <ItemTemplate>
                            <%#Eval("startdate","{0:dd.MM.yyyy}") %>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="d2" runat="server" Text='<%#Bind("startdate","{0:MM.dd.yyyy}") %>'></asp:TextBox>                            
                             <ajaxToolkit:CalendarExtender TargetControlID="d2" Format="MM.dd.yyyy" ID="CalenderExtender1"
                                runat="server">
                                </ajaxToolkit:CalendarExtender>
                        </EditItemTemplate>
                    </asp:TemplateField>       
                    <asp:TemplateField HeaderText="eventdate">
                        <ItemTemplate>
                            <%#Eval("eventdate","{0:dd.MM.yyyy}") %>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="d3" runat="server" Text='<%#Bind("eventdate","{0:MM.dd.yyyy}") %>'></asp:TextBox>                              
                               <ajaxToolkit:CalendarExtender TargetControlID="d3" Format="MM.dd.yyyy" ID="CalenderExtender2"
                                runat="server">
                            </ajaxToolkit:CalendarExtender>
                        </EditItemTemplate>
                    </asp:TemplateField>                                                  
                     <asp:BoundField DataField="contactperson" HeaderText="contactperson" SortExpression="contactperson" />
                    <asp:BoundField DataField="contactnumber" HeaderText="contactnumber" SortExpression="contactnumber" />
                    <asp:BoundField DataField="updatedby" HeaderText="Last Updated By" SortExpression="updatedby"
                        ReadOnly="True" />
                    <asp:BoundField DataField="updateddate" HeaderText="Last Updated Date" SortExpression="updateddate"
                        ReadOnly="True" />
                   
                    <asp:BoundField DataField="ispublic" HeaderText="ispublic" SortExpression="ispublic" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:KallivayalilDB %>"
                DeleteCommand="delete from tblspecialevents where  socialeventid=?" ProviderName="<%$ ConnectionStrings:KallivayalilDB.ProviderName %>"
               SelectCommand="Select socialeventid,eventname,eventtype,eventdetails,startdate,eventdate,contactperson,contactnumber,ispublic,updatedby,updateddate from tblspecialevents"
                UpdateCommand="update tblspecialevents set eventname=?,eventtype=?,eventdetails=?,startdate=STR_TO_DATE(?,GET_FORMAT(DATE,'USA')),eventdate=STR_TO_DATE(?,GET_FORMAT(DATE,'USA')),contactperson=?,contactnumber=?,ispublic=? where socialeventid =?">
            </asp:SqlDataSource>
        </div>
    </div>
</asp:Content>
