using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class ModifyEvent : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
       // GridView1.AutoGenerateEditButton = true;
        //GridView1.AutoGenerateDeleteButton = true;        
       // BindData();
        
    }

    private void BindData()
    {
        AccessDB dbObj = new AccessDB();
        dbObj.Open();
        dbObj.Query = string.Format("Select * from tblspecialevents");
        dbObj.ExecuteQuery();
        GridView1.DataSource = dbObj.Dataset;
        GridView1.DataBind();
        dbObj.Close();

    }
    protected void GridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
    {
        Session.Add("selEventIndex", GridView1.DataKeys[GridView1.EditIndex].Value);
    }


    protected void GridView1_RowUpdated(object sender, GridViewUpdatedEventArgs e)
    {
        AccessDB dbObj = new AccessDB();
        dbObj.Open();
        dbObj.Query = string.Format("update tblspecialevents set updatedby = '{0}' , updateddate = curdate() where socialeventid = {1}", Session["UserName"], Session["selEventIndex"]);
        dbObj.ExecuteNonQuery();
        dbObj.Close();

    }
}
